Adds error message if tag doesn't verify
Requested by @kushaldas during review. We can't easily pass through the stderr
from the git verify process, since we redirect that stderr to stdout so
that grep can inspect it. So let's just detect the failure and report
that the tag failed to verify, which is accurate, albeit neither
explicit nor verbose.

diff --git a/scripts/build-debianpackage b/scripts/build-debianpackage
--- a/scripts/build-debianpackage
+++ b/scripts/build-debianpackage
@@ -67,8 +67,11 @@ function verify_git_tag() {
     d="$1"
     t="$2"
     prod_fingerprint="22245C81E3BAEB4138B36061310F561200F4AD77"
-    git -C "$build_dir" tag --verify "$PKG_VERSION" 2>&1 \
-        | grep -q -F "using RSA key $prod_fingerprint"
+    if ! git -C "$build_dir" tag --verify "$PKG_VERSION" 2>&1 \
+        | grep -q -F "using RSA key $prod_fingerprint" ; then
+        echo "Failed to verify $PKG_VERSION, not signed with $prod_fingerprint" >&2
+        exit 2
+    fi
 }
 
 # Dynamically generate a tarball, from the Python source code,
