Rename "PKG_GITREF" to "SD_PKG_GITREF"
This will be exported in the `.buildinfo` file so let's prefix it with
"SD" to make it abundantly clear this is our environment variable and
reduce the risk of collision.

There don't appear to be any other users of this besides humans, so I
have not added in any backwards-compatibility support for the old name.

diff --git a/scripts/build-debianpackage b/scripts/build-debianpackage
--- a/scripts/build-debianpackage
+++ b/scripts/build-debianpackage
@@ -23,8 +23,8 @@ if [[ -z "${PKG_NAME:-}" ]]; then
 fi
 
 if [[ -z "${PKG_PATH:-}" ]]; then
-    if  [[ -z "${PKG_GITREF:-}" ]]; then
-        echo "Set PKG_PATH or PKG_GITREF";
+    if  [[ -z "${SD_PKG_GITREF:-}" ]]; then
+        echo "Set PKG_PATH or SD_PKG_GITREF";
         exit 1
     fi
 fi
@@ -73,12 +73,12 @@ function setup_source_tree() {
     rm -rf "$build_dir"
     git clone "$repo_url" "$build_dir"
 
-    if [[ -n "${PKG_GITREF:-}" ]]; then
-        # if PKG_GITREF looks like a release tag, check for a release signature
-        [[ "$PKG_GITREF" =~ ^(0|[1-9][0-9]*).(0|[1-9][0-9]*).(0|[1-9][0-9]*)$ ]] && verify_git_tag "$build_dir" "$PKG_GITREF"
-        git -C "$build_dir" checkout "$PKG_GITREF"
+    if [[ -n "${SD_PKG_GITREF:-}" ]]; then
+        # if SD_PKG_GITREF looks like a release tag, check for a release signature
+        [[ "$SD_PKG_GITREF" =~ ^(0|[1-9][0-9]*).(0|[1-9][0-9]*).(0|[1-9][0-9]*)$ ]] && verify_git_tag "$build_dir" "$SD_PKG_GITREF"
+        git -C "$build_dir" checkout "$SD_PKG_GITREF"
     else
-        echo "Neither PKG_PATH nor PKG_GITREF were defined - please specify one" >&2
+        echo "Neither PKG_PATH nor SD_PKG_GITREF were defined - please specify one" >&2
         exit 2
     fi
 }
@@ -152,10 +152,10 @@ export SOURCE_DATE_EPOCH
 # Grab package version from changelog
 CHANGELOG_VERSION=$(dpkg-parsechangelog --show-field Version)
 
-# If PKG_GITREF is set and is a release tag, check that it matches the version in debian/changelog
-if [[ -n "${PKG_GITREF:-}" ]] && [[ "${PKG_GITREF:-}" =~ ^(0|[1-9][0-9]*).(0|[1-9][0-9]*).(0|[1-9][0-9]*)$ ]]; then
-    if ! [[ "$PKG_GITREF+$VERSION_CODENAME" == "$CHANGELOG_VERSION" ]]; then
-        echo "Changelog version is $CHANGELOG_VERSION, but the provided tag is $PKG_GITREF. Aborting build."
+# If SD_PKG_GITREF is set and is a release tag, check that it matches the version in debian/changelog
+if [[ -n "${SD_PKG_GITREF:-}" ]] && [[ "${SD_PKG_GITREF:-}" =~ ^(0|[1-9][0-9]*).(0|[1-9][0-9]*).(0|[1-9][0-9]*)$ ]]; then
+    if ! [[ "$SD_PKG_GITREF+$VERSION_CODENAME" == "$CHANGELOG_VERSION" ]]; then
+        echo "Changelog version is $CHANGELOG_VERSION, but the provided tag is $SD_PKG_GITREF. Aborting build."
         exit 2
     fi
 fi
